#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# ============================================================
# BUILDER: Setup.sh Generator
# Combines modular components into a single distributable script
# ============================================================

OUTPUT_FILE="setup.sh"
SRC_DIR="./src"

echo "🏗️  Building monolithic setup.sh from modules..."

# Start with the base header using a simple echo to avoid heredoc issues
echo "#!/usr/bin/env bash" > "$OUTPUT_FILE"
echo "set -euo pipefail" >> "$OUTPUT_FILE"
echo "IFS=$'\n\t'" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "# Generated by Architect_Dev_Prime Builder" >> "$OUTPUT_FILE"
echo "# Project: hg680p-printserver" >> "$OUTPUT_FILE"
echo "# Date: $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Append modules in order
for mod in mod_01_env_core.sh mod_02_network_os.sh mod_03_infrastructure.sh mod_04_services_deploy.sh mod_05_final_touch.sh; do
    echo "Adding $mod..."
    cat "$SRC_DIR/$mod" >> "$OUTPUT_FILE"
    echo -e "\n" >> "$OUTPUT_FILE"
done

chmod +x "$OUTPUT_FILE"
echo "✅ Successfully built $OUTPUT_FILE"
